#pragma once
#include <osg/Array>
#include <osg/MatrixTransform>
#include <osg/Geode>
#include <osg/Geometry>
#include <osg/Group>
#include <osg/GraphicsContext>
#include <osg/Object>
#include <osg/Program>
#include <osg/PrimitiveSet>
#include <osg/PatchParameter>
#include <osg/ShapeDrawable>
#include <osg/State>
#include <osg/Texture2D>
#include <osg/Texture3D>
#include <osg/PolygonMode>
#include <osgDB/ReadFile>
#include <osgGA/TrackballManipulator>
#include <osgGA/EventHandler>
#include <osgGA/GUIEventAdapter>
#include <osgGA/GUIActionAdapter>
#include <osgViewer/Viewer>
#include <osgViewer/api/Win32/GraphicsWindowWin32>
#include <osgViewer/ViewerEventHandlers>
#include <osgUtil/Optimizer>